language: node_js
node_js: 
  - "10.7.0"

notifications:
  email:
    recipients:
      - yorewole@gmail.com
    on_success: never
    on_failure: never

cache:
  yarn: true
  directories:
    - "node_modules"

script: yarn test